### ISSUE TITLE
Filebrowser exits with code 1 whenever SIGTERM is received

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/filebrowser-wrapper#15]
Should exit with code 0 as long as nothing went wrong

Need to either handle this and translate to 0 in the wrapper, or submit a fix to upstream 

Filed an issue with filebrowser here https://github.com/filebrowser/filebrowser/issues/1633

**Comment by chrisguida** [comment]
Appears to have been fixed here: 3c2e6cd16a56026b194421a79a1cbd3c4f7e24c3

**Comment by ProofOfKeags** [comment]
reassigning to @chrisguida since he has capacity.

**Comment by chrisguida** [comment]
Fixed by 3c2e6cd16a56026b194421a79a1cbd3c4f7e24c3
