### ISSUE TITLE
Crashed instead of shutting down gracefully - first itme only.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/filebrowser-wrapper#16]
![Screen Shot 2021-12-02 at 9 02 23 PM](https://user-images.githubusercontent.com/45926711/144548351-c6df88a9-d200-421e-9820-c3c3c93665c0.png)

**Comment by elvece** [comment]
Resolved [here](https://github.com/Start9Labs/filebrowser-wrapper/commit/a4c19413d75313951e13a97de932d97f51606921) and pushed to 0.3.0 beta registry. @BitcoinMechanic please update filebrowser by either uninstalling and reinstalling or running `embassy-cli package install filebrowser` from the command line when ssh'd into your Embassy.

**Comment by BitcoinMechanic** [comment]
Thanks. Will test later.

**Comment by BitcoinMechanic** [comment]
Working now, gj!
