### ISSUE TITLE
Firefox: Auto suggests a password when sharing a file (whatever the saved password is to log in to FB)

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/filebrowser-wrapper#18]
![Screen Shot 2021-12-09 at 10 24 39 PM](https://user-images.githubusercontent.com/45926711/145527427-8da00d3b-bacf-4c99-9cc8-509a127e195c.png)

**Comment by chrisguida** [comment]
This is a bug with filebrowser. Please file an issue upstream github.com/filebrowser/filebrowser
