### ISSUE TITLE
FIlebrowser creating invalid share links

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/filebrowser-wrapper#5]
links currently say "ext-onion://" instead of "http://". I'm guessing .local needs to be updated as well.

**Comment by chrisguida** [comment]
This is not happening anymore for me. @ProofOfKeags why was this issue reopened?

**Comment by ProofOfKeags** [comment]
Given that I closed this and immediately reopened, my guess is that it was a mistake. Close at your discretion.
